### ISSUE TITLE
oss可以上传成功，但是有点慢

### ISSUE THREAD

**Issue by dingxiaowu** [htliang128/arkts_oss#2]
1 你好，一直关注这个oss，终于可以使用，感谢。 
2 在用的过程中发现上传太慢了。一个800k图片，竟然要20s。当然也有可能是我使用方法不对。
3 使用如下
   （1）创建请求
   let putObjectRequest = new PutObjectRequest(buckName, objectKey, new ByteArrayInputStream(ImageData))
   await ossClient.putObject(putObjectRequest)
   创建 PutObjectRequest ，因为我发现我传File 报错，就干脆传,InputStream
    (2) 定位你的代码  HttpRequestFactory  中  createHttpRequestOptionsBuilder 方法
         这一句 代码 httpRequestOptions.setExtraData(content.readAllBytes().buffer); 转换太耗时了。
4 不过我修改了下你的代码，一直带上 ArrayBuffer 数据 ，最后 设置到 setExtraData 中。解决耗时了。
5 我只是提下。

**Comment by htliang128** [comment]
收到🫡，下个版本优化

**Comment by htliang128** [comment]
为了适配分段上传，后面会分开处理

**Comment by htliang128** [comment]
fixed
